repos:
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.18.0
    hooks:
      - id: gitlint
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.1
    hooks:
      - id: bandit
        language_version: python3
        args:
          [
            -ll,
            '-x=node_modules,tests',
            '-s=B101,B301,B403,B308,B303,B608',
            '-b=bandit_baseline.json',
          ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
        args: ['--markdown-linebreak-ext=md']
      - id: check-json
        exclude: (\.jshintrc)
      - id: check-yaml
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: end-of-file-fixer
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.11
    hooks:
      - id: forbid-crlf
      - id: remove-crlf
      - id: forbid-tabs
      - id: remove-tabs
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        name: Flake8
        # Python 3.6 is used here as flake8 is using whatever language it's run on
        # as the language to check against. As we are running 3.6 on production
        # it's important to run checks also agains 3.6.
        language_version: python3
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.1.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: .*/tests/.*|.*/locale(s*)/.*
        language_version: python3
